format = """$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$line_break\
$python\
$character"""

[fill]
symbol = ''

[directory]
style = "#91a8ba"
truncation_length = 1
truncation_symbol = ""

[character]
success_symbol = "[❯](#d3869b)"
error_symbol = "[❯](#ec6b64)"
vimcmd_symbol = "[❮](#a9b665)"

[git_branch]
format = "[$branch]($style)"
style = "#404344"

[git_status]
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed )]($style)"
style = "#404344"
# conflicted = " 󰞇 "
# untracked = "  "
# modified = "  "
# staged = "  "
# renamed = "  "
# deleted = "  "
# stashed = " ≡ "
#
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#404344"

[cmd_duration]
format = "[$duration]($style) "
style = "#e0c080"

[python]
format = "[$virtualenv]($style)"
style = "#404344"
