vim.cmd [[inoremap <M-BS> <C-w>]]
vim.cmd [[inoremap <C-Z> <Esc>ui]]
vim.cmd [[inoremap <C-Z> <Esc>ui]]
vim.cmd [[inoremap <C-S-Z> <Esc><C-r>]]
vim.cmd [[nnoremap H :bp<enter>]]
vim.cmd [[nnoremap L :bn<enter>]]
